### SQL server try out ###
#spring.datasource.url=jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SR_GAMES
#spring.datasource.username=SpaceRaze
#spring.datasource.password=SpaceRaze


#spring.datasource.game.jdbcUrl=jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SR_GAME
#spring.datasource.game.username=SpaceRaze
#spring.datasource.game.password=SpaceRaze
#spring.jpa.game.hibernate.ddl-auto = update

spring.datasource.map.jdbcUrl=jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SR_MAP
spring.datasource.map.username=SpaceRaze
spring.datasource.map.password=SpaceRaze
spring.datasource.map.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.map.hibernate.ddl-auto = update

spring.datasource.world.jdbcUrl=jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SR_WORLD
spring.datasource.world.username=SpaceRaze
spring.datasource.world.password=SpaceRaze
spring.datasource.world.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.world.hibernate.ddl-auto = update



spring.datasource.user.jdbcUrl=jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=SR_USER
spring.datasource.user.username=SpaceRaze
spring.datasource.user.password=SpaceRaze
spring.datasource.user.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.user.hibernate.ddl-auto = update



#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
##spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.format_sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto = update
##spring.jpa.hibernate.ddl-auto = validate




### H2(minnesdatabas) databas
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

####spring.datasource.url=jdbc:h2:file:/data/demo
#spring.jpa.show-sql=true
#spring.h2.console.enabled=true
#old.datapath = \\
datapath =C:\\utveckling\\data\\




